### ISSUE TITLE
Sample application doesn't work

### ISSUE THREAD

**Issue by keemor** [OpenNTF/dojo-webpack-plugin-sample#47] opened 2017-11-15 10:06 UTC
Just to let you know that Sample application doesn't work:

https://openntf.github.io/dojo-webpack-plugin-sample/test.html

Uncaught Error: Module not found: dijit/nls/pl/common

Cheers,

**Comment by chuckdumont** [comment] 2017-11-15 12:31
Thanks.  I hadn't yet updated the sample to the latest version of the plugin.  The issue you encountered was caused by https://github.com/OpenNTF/dojo-webpack-plugin/issues/69 and was fixed in 2.1.4.  I've updated the sample to use 2.1.5 of the plugin so it should work for you now.

**Closed by chuckdumont** 2017-11-15 12:31 UTC
